#!/bin/bash

# Description: Script to build KOOMPI-Toolchain
# URL: 
# Maintainer: HangsiaHong, hangsia@koompi.org
# Organization: KOOMPI, koompi.com
# Depends on:


main() {
    ./scripts/kfs-toolchain && sudo ./scripts/kfs-base && sudo ./scripts/kfs-mkiso

}

main

echo "FINISHED"