# Begin /etc/bashrc
# Written for KOOMPI From Scratch
# by Hong Hangsia <hangsia@koompi.org>

source /etc/bash_aliases

# System wide aliases and functions.
[[ $- != *i* ]] && return

# System wide environment variables and startup programs should go into
# /etc/profile.  Personal environment variables and startup programs
# should go into ~/.bash_profile.  Personal aliases and functions should
# go into ~/.bashrc

# Provides colored /bin/ls and /bin/grep commands.  Used in conjunction
# with code in /etc/profile.

alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Provides prompt for non-login shells, specifically shells started
# in the X environment. [Review the KFS archive thread titled
# PS1 Environment Variable for a great case study behind this script
# addendum.]

PS1="\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[35m\]\h\[\e[m\]\[\e[34m\]\\[\e[m\]\[\e[36m\]:\w\[\e[m\]\[\e[35m\]\`parse_git_branch\`\[\e[m\] \n> "


# check command history
function h() {
    history | grep $1 ;
}

# End /etc/bashrc
